#!/usr/bin/env python3
"""Prepare a single Wan overfit sample.

If DiffSynth preprocessing is available, prefer producing real Wan VAE latents
and UMT5 context externally and saving them in the same `.pt` schema. This
script is a fallback smoke-sample builder: it can derive deterministic pseudo
latents from a short video via ffmpeg, plus deterministic context embeddings
from the prompt. The training loss and model path remain identical to the real
pre-encoded data path.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import subprocess
from pathlib import Path

import torch

from wan.model.config import PRESETS


def _read_video_as_latents(video: str, channels: int, frames: int, height: int, width: int):
    import numpy as np

    cmd = [
        os.environ.get("FFMPEG_BIN", "ffmpeg"),
        "-nostdin",
        "-hide_banner",
        "-loglevel",
        "error",
        "-i",
        video,
        "-vf",
        f"fps=4,scale={width}:{height}:force_original_aspect_ratio=increase,crop={width}:{height}",
        "-frames:v",
        str(frames),
        "-f",
        "rawvideo",
        "-pix_fmt",
        "rgb24",
        "-",
    ]
    raw = subprocess.check_output(cmd)
    arr = np.frombuffer(raw, dtype=np.uint8)
    expected = frames * height * width * 3
    if arr.size < expected:
        raise RuntimeError(f"ffmpeg returned {arr.size} bytes, expected at least {expected}")
    arr = arr[:expected].reshape(frames, height, width, 3).astype("float32") / 127.5 - 1.0
    lat = torch.from_numpy(arr).permute(3, 0, 1, 2).contiguous()
    if channels <= 3:
        lat = lat[:channels]
    else:
        extra = lat.mean(dim=0, keepdim=True).repeat(channels - 3, 1, 1, 1)
        lat = torch.cat([lat, extra], dim=0)
    return lat


def _random_context(prompt: str, seq_len: int, text_dim: int):
    digest = hashlib.sha256(prompt.encode("utf-8")).digest()
    seed = int.from_bytes(digest[:8], "little") % (2**31)
    gen = torch.Generator(device="cpu")
    gen.manual_seed(seed)
    return torch.randn(seq_len, text_dim, generator=gen) * 0.02


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    parser.add_argument("--video", default=None)
    parser.add_argument("--prompt", default="a short real-world video clip")
    parser.add_argument("--preset", default="tiny", choices=sorted(PRESETS))
    parser.add_argument("--latent-frames", type=int, default=5)
    parser.add_argument("--latent-height", type=int, default=16)
    parser.add_argument("--latent-width", type=int, default=16)
    parser.add_argument("--context-len", type=int, default=32)
    parser.add_argument("--seed", type=int, default=1234)
    args = parser.parse_args()

    cfg = PRESETS[args.preset]
    if args.video:
        latents = _read_video_as_latents(
            args.video,
            channels=cfg.in_dim,
            frames=args.latent_frames,
            height=args.latent_height,
            width=args.latent_width,
        )
        video_path = str(Path(args.video).resolve())
    else:
        gen = torch.Generator(device="cpu")
        gen.manual_seed(args.seed)
        latents = torch.randn(
            cfg.in_dim,
            args.latent_frames,
            args.latent_height,
            args.latent_width,
            generator=gen,
        )
        video_path = ""

    context = _random_context(args.prompt, args.context_len, cfg.text_dim)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "input_latents": latents,
            "context": context,
            "prompt": args.prompt,
            "video_path": video_path,
            "schema": "wan_overfit_preencoded_v1",
            "note": "Pseudo latents unless generated by an external Wan VAE preprocessing path.",
        },
        output,
    )
    print(f"saved {output}")
    print(f"latents={tuple(latents.shape)} context={tuple(context.shape)} video={video_path}")


if __name__ == "__main__":
    main()
